import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { isDeepStrictEqual } from 'node:util'
import { BENCH_ROOT } from './bench.mjs'
import { createCollectionManifest } from './collection.mjs'
import { assert, atomicWrite, readLocal } from './audit-io.mjs'
import { sha256 } from './mp3.mjs'
import { planSyncAudition } from '../../apps/sfx-bench/src/sync.js'
import { normalizeSyncFeedback } from '../../apps/sfx-bench/src/syncFeedback.js'
import { validateFinalReviewEvidence, THIRD_FINAL_REVIEW, THIRD_FINAL_FEEDBACK, THIRD_REVIEW_PLAYBACK_FILES } from './sync-batch.mjs'

export const ACCEPTED_BATCH = 'tools/audio-import/review/sync-batch-001.final.json'
export const ACCEPTED_BATCHES = Object.freeze([ACCEPTED_BATCH, 'tools/audio-import/review/sync-batch-002.final.json', 'tools/audio-import/review/sync-batch-003.final.json'])
const NATIVE_EVIDENCE = 'tools/audio-import/review/sync-batch-002.native-01.json'
const OUTPUT = 'packages/battle-sfx/src/accepted-runtime.generated.js'
const IDS = {
  'sync-001': ['bodyslam', 'aerialace', 'hydropump', 'thunderbolt', 'triplekick', 'absorb'],
  'sync-002': ['icebeam', 'psychic', 'flamethrower', 'shadowball', 'rockslide', 'gigadrain'],
  'sync-003': ['surf', 'watergun', 'crunch', 'thunderpunch', 'swift', 'calmmind'],
}
const generatedSource = catalog => `// Generated by tools/audio-import/accepted-runtime.mjs. User-accepted final versions.\nexport default ${JSON.stringify(catalog)}\n`

/** Final review decisions compile separately from historical pilot/draft packs.
 * Timing uses the actual native seconds heard in the accepted comparison. */
export function compileAcceptedRuntime({ final, manifest, finalBytes, nativeEvidenceBytes, reviewEvidenceBytes, feedbackEvidenceBytes, playbackPins }) {
  assert(final?.schemaVersion === 1 && final.kind === 'battle-sfx-final-batch' && Object.hasOwn(IDS, final.batchId), 'Unsupported final sound batch')
  assert(final.approval?.source === 'user-message' && typeof final.approval.text === 'string' && final.approval.text.length > 0
    && /^\d{4}-\d{2}-\d{2}$/.test(final.approval.date) && /^[a-f0-9]{64}$/.test(final.reviewedRevision), 'Final batch needs explicit user approval and review provenance')
  assert(Buffer.isBuffer(finalBytes) && isDeepStrictEqual(JSON.parse(finalBytes.toString()), final), 'Final batch bytes differ from approval input')
  assert(Array.isArray(final.moves) && isDeepStrictEqual(final.moves.map(move => move.id), IDS[final.batchId]), 'Final batch must contain the six accepted moves exactly once')
  let measured
  if (final.batchId === 'sync-002') {
    assert(final.nativeEvidence?.path === NATIVE_EVIDENCE && Buffer.isBuffer(nativeEvidenceBytes)
      && sha256(nativeEvidenceBytes) === final.nativeEvidence.sha256, 'Final native evidence bytes changed')
    const evidence = JSON.parse(nativeEvidenceBytes)
    measured = normalizeSyncFeedback(evidence, { id: final.batchId, revision: final.reviewedRevision,
      moves: final.moves.map(move => ({ ...move, candidate: move.plan })) })
    assert(isDeepStrictEqual(measured, evidence), 'Final native evidence contains invalid tuning')
  }
  if (final.batchId === 'sync-003') measured = validateFinalReviewEvidence({ final,
    batch: { id: final.batchId, moves: final.moves.map(move => ({ ...move, candidate: move.plan })) },
    reviewEvidenceBytes, feedbackEvidenceBytes, playbackPins })
  const moves = {}, fxMoves = {}, assets = {}
  function sound(asset, captured, plan, native, visual, label) {
    assert(asset && asset.sha256 === captured?.sha256 && asset.bytes === captured.bytes
      && isDeepStrictEqual(asset.decoded, captured.decoded), `Final sound source/PCM changed: ${label}`)
    assert(native && typeof native.userAgent === 'string' && !/Edg\/|OPR\//.test(native.userAgent), `Unsupported reviewed browser: ${label}`)
    const chrome = /\bChrome\/(\d+\.\d+\.\d+\.\d+)/.exec(native.userAgent)
    assert(chrome, `Final mapping requires a measured Chrome decoder: ${label}`)
    const regions = planSyncAudition(plan, native, visual)
    assert(regions.every(region => region.gainDb <= 0 && region.delaySeconds + region.endSeconds - region.startSeconds <= 120), 'Accepted sounds must remain bounded and attenuation-only')
    assert(Math.abs(native.durationSeconds - asset.decoded.sampleFrames / asset.decoded.sampleRate) <= .1, `Final native duration differs from source: ${label}`)
    const { sampleRate, sampleFrames, channels, peak } = asset.decoded
    assets[asset.id] = { id: asset.id, file: `${asset.sha256}.mp3`, bytes: asset.bytes, sha256: asset.sha256,
      mime: 'audio/mpeg', reference: { sampleRate, sampleFrames, channels, peak } }
    return { browser: 'Chrome', version: chrome[1], sampleRate: native.sampleRate, sampleFrames: native.sampleFrames }
  }
  for (const move of final.moves) {
    const subject = manifest.subjects.find(subject => subject.kind === 'move' && subject.phase === 'attack' && subject.id === move.id)
    const asset = manifest.assets[move.asset?.id]
    assert(subject?.fxId === move.fxId && asset && subject.assetIds.includes(asset.id), `Unknown final sound mapping: ${move.id}`)
    assert(subject.visualRevision === move.visual?.visualRevision && subject.durationSeconds === move.visual.durationSeconds, `Final visual revision changed: ${move.id}`)
    const nativeCompatibility = sound(asset, move.asset, move.plan, move.native, move.visual, move.id)
    const record = measured?.records.find(row => row.moveId === move.id)
    if (measured) assert(isDeepStrictEqual(record.plan, move.plan) && isDeepStrictEqual(record.native, move.native), `Final measured base plan changed: ${move.id}`)
    const needsAccent = final.batchId === 'sync-002' && move.id === 'psychic'
    assert(Boolean(move.accent) === needsAccent, 'Only the accepted Psychic must have an impact accent')
    assert(Boolean(move.visualAccent) === (final.batchId === 'sync-003' && move.id === 'thunderpunch'), 'Only the accepted Thunder Punch must have a visual accent')
    let accent
    if (needsAccent) {
      assert(move.accent.asset?.id === 'source.hit-normal-damage'
        && isDeepStrictEqual(move.accent.segment, { startSeconds: 0, endSeconds: null, soundAnchorSeconds: .1, cueSeconds: .95, gainDb: -6 }), 'Final Psychic accent differs from the reviewed whole impact')
      assert(record.accent && isDeepStrictEqual(record.accent.native, move.accent.native), 'Final accent native measurement changed')
      accent = { assetId: move.accent.asset.id, segment: structuredClone(move.accent.segment), nativeCompatibility:
        sound(manifest.assets[move.accent.asset.id], move.accent.asset, { visualRate: move.plan.visualRate, segments: [move.accent.segment] }, move.accent.native, move.visual, `${move.id} accent`) }
    }
    moves[move.id] = { moveId: move.id, fxId: move.fxId, phase: 'attack', assetId: asset.id,
      reviewStatus: 'accepted-sync', visualRevision: move.visual.visualRevision,
      visualRate: move.plan.visualRate, segments: structuredClone(move.plan.segments), playbackRate: 1,
      visualDurationSeconds: move.visual.durationSeconds,
      nativeCompatibility, ...(accent ? { accent } : {}), ...(move.visualAccent ? { visualAccent: structuredClone(move.visualAccent) } : {}) }
    fxMoves[move.fxId] = move.id
  }
  const catalog = { schemaVersion: 1, kind: 'battle-sfx-accepted-runtime', provenance: {
    batchId: final.batchId, finalBatchSha256: sha256(finalBytes), reviewedRevision: final.reviewedRevision,
    approvalSource: final.approval.source, finalizedOn: final.approval.date,
  }, assets, moves, fxMoves }
  return { catalog, generated: generatedSource(catalog) }
}

export async function generateAcceptedRuntime({ root = BENCH_ROOT, check = false } = {}) {
  const manifest = await createCollectionManifest({ root })
  const catalogs = []
  for (const path of ACCEPTED_BATCHES) {
    const finalBytes = await readLocal(root, path), final = JSON.parse(finalBytes)
    catalogs.push(compileAcceptedRuntime({ final, finalBytes, manifest,
      ...(final.batchId === 'sync-002' ? { nativeEvidenceBytes: await readLocal(root, NATIVE_EVIDENCE) } : {}),
      ...(final.batchId === 'sync-003' ? { reviewEvidenceBytes: await readLocal(root, THIRD_FINAL_REVIEW),
        feedbackEvidenceBytes: await readLocal(root, THIRD_FINAL_FEEDBACK),
        playbackPins: await Promise.all(THIRD_REVIEW_PLAYBACK_FILES.map(async path => ({ path, sha256: sha256(await readLocal(root, path)) }))),
      } : {}) }).catalog)
  }
  const catalog = { schemaVersion: 1, kind: 'battle-sfx-accepted-runtime', provenance: { batches: catalogs.map(row => row.provenance) }, assets: {}, moves: {}, fxMoves: {} }
  for (const row of catalogs) for (const field of ['assets', 'moves', 'fxMoves']) for (const [id, value] of Object.entries(row[field])) {
    assert(!Object.hasOwn(catalog[field], id) || field === 'assets' && isDeepStrictEqual(catalog[field][id], value), `Duplicate accepted runtime ${field}: ${id}`)
    catalog[field][id] = value
  }
  const result = { catalog, generated: generatedSource(catalog) }
  const outputs = [{ path: OUTPUT, bytes: Buffer.from(result.generated) }]
  // Copy verified original bytes into hash-addressed delivery. No trimming,
  // re-encoding, source replacement or deletion of another move's shared file.
  for (const asset of Object.values(catalog.assets)) {
    const bytes = await readLocal(root, `public/sound_effects/${manifest.assets[asset.id].file}`)
    assert(bytes.length === asset.bytes && sha256(bytes) === asset.sha256, `Accepted runtime source missing or altered: ${asset.id}`)
    outputs.push({ path: `public/audio/sfx/${asset.file}`, bytes })
  }
  for (const { path, bytes } of outputs) {
    if (check) assert((await readLocal(root, path, true))?.equals(bytes), `Accepted runtime output is stale: ${path}; run npm run sfx:accepted`)
    else await atomicWrite(root, path, bytes)
  }
  return result
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  try {
    const args = process.argv.slice(2)
    assert(args.length <= 1 && args.every(arg => arg === '--check'), 'Usage: node tools/audio-import/accepted-runtime.mjs [--check]')
    const result = await generateAcceptedRuntime({ check: args.includes('--check') })
    console.log(`${args.includes('--check') ? 'Verified' : 'Generated'} ${Object.keys(result.catalog.moves).length} accepted final move versions; source recordings unchanged.`)
  } catch (error) { console.error(error.message); process.exitCode = 1 }
}
